### ISSUE TITLE
FHIR-NHS-BOOKING-API - Guidance for 3rd party contact details

### ISSUE THREAD

**Issue by davidaruddy** [nhsd-a2si/docs-uec-appts#343]
Updated guidance around Patient.Telecom to the following:

Either Patient.Telecom OR Patient.Contact.Telecom + Patient.Contact.Name need to be populated.

**Comment by RichardWardNHSD** [comment]
@davidaruddy - Do you want me to have a look at this?

**Comment by davidaruddy** [comment]
Yes, although, we cannot make any changes to the spec site directly (we have to go through IOPS team. Lets chat in a bit on the 12:30 call.
