### ISSUE TITLE
WHAT ARE WE DOING?:  Working with GP Connect

### ISSUE THREAD

**Issue by AdnanRiazUEC** [nhsd-a2si/docs-uec-appts#96]
Should we not include guidance for 111 IT Suppliers in terms of what they need to do when working with GP Connect.  So what do the suppliers need to do in terms of workflow, filtering, reporting etc

**Comment by davidaruddy** [comment]
I agree with this, I think we do need to put something in covering GP Connect. However I think this is a whole new section with a lot of content. I will move this out of review for v0.1.5 and put it on the main backlog as a feature for a future release.

**Comment by AdnanRiazUEC** [comment]
Thanks.  Would this be a priority to do as we have both ic24 and advanced working on this?

Regards

Adnan Riaz

**Comment by davidaruddy** [comment]
Yes, I can make this a priority and put it into the next release along with the reporting stuff.
