### ISSUE TITLE
FUNCTIONAL SCOPE: Reporting

### ISSUE THREAD

**Issue by AdnanRiazUEC** [nhsd-a2si/docs-uec-appts#98]
Monitoring, Analytics and Reporting

What is expected to be handled locally:?
What are the national metrics?
What is the mechanism for sharing?

**Comment by davidaruddy** [comment]
There is going to be a major elaboration and update to the reporting section. This will be in a future release (likely the next one). Therefore I am going to move this to the main backlog, there are a couple of existing issues covering reporting.
